=== andreas-bradahl/test.rockitizer/examples/splitcustomerApp/CustomerBatchSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="rockit.customerBatch.simpleCustomer" xmlns:p="rockit.customerBatch.simpleCustomer" xmlns="rockit.customerBatch.simpleCustomer">
  	<xsd:element name="customers" type="customersType"/>

	<xsd:complexType name="customersType">
    	<xsd:sequence>
      		<xsd:element name="customer" type="customerType" minOccurs="1" maxOccurs="unbounded"/>
    	</xsd:sequence>
  	</xsd:complexType>
  
   	<xsd:complexType name="customerType">
    	<xsd:sequence>
			<xsd:element name="person">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="name" type="xsd:string" minOccurs="1"/>
      					<xsd:element name="surname" type="xsd:string" minOccurs="1"/>
						<xsd:element name="addresses" minOccurs="0" maxOccurs="1">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="address" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>      
			    	</xsd:sequence>
			    </xsd:complexType>
			</xsd:element>
    	</xsd:sequence>
  	</xsd:complexType>
</xsd:schema>

=== andreas-bradahl/test.rockitizer/examples/splitcustomerApp/testfiles/CustomerBatch.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:customers xmlns:p="rockit.customerBatch.simpleCustomer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="rockit.customerBatch.simpleCustomer CustomerBatchSchema.xsd ">
    <customer>
        <person>
            <name>Lisa</name>
            <surname>Wilke</surname>
            <addresses>
                <address>Stuttgart</address>
            </addresses>
        </person>
    </customer>
    <customer>
        <person>
            <name>Martin</name>
            <surname>Test</surname>
            <addresses>
                <address>Mannheim</address>
                <address>Konstanz</address>
            </addresses>
        </person>
    </customer>
    <customer>
        <person>
            <name>Max</name>
            <surname>Mustermann</surname>
            <addresses>
                <address>München</address>
            </addresses>
        </person>
    </customer>
    <customer>
        <person>
            <name>Inga</name>
            <surname>Mustermann</surname>
            <addresses>
                <address>Stockach</address>
                <address>Überlingen</address>
                <address>Konstanz</address>
            </addresses>
        </person>
    </customer>
</p:customers>
